cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

variables:
  # output upload and download progress every 2 seconds
  TRANSFER_METER_FREQUENCY: "2s"

  # Use fast compression for artifacts, resulting in larger archives
  ARTIFACT_COMPRESSION_LEVEL: "fast"

  # Use no compression for caches
  CACHE_COMPRESSION_LEVEL: "fastest"

  # Set maximum duration of cache upload and download
  CACHE_REQUEST_TIMEOUT: 5

stages:
  - build
  - code
  - test

install: # Installation des dépendances du projet
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  tags:
    - php81
    - composer

code-fixer: # Vérification du code PHP
  stage: code
  dependencies:
    - install
  script:
    - vendor/bin/php-cs-fixer fix --diff --dry-run
  tags:
    - php81
    - composer

lint-yaml: # Vérification du YAML
  stage: code
  dependencies:
    - install
  script:
    - bin/console lint:yaml config
  tags:
    - php81
    - composer

lint-twig: # Vérification du Twig
  stage: code
  dependencies:
    - install
  script:
    - bin/console lint:twig templates
  tags:
    - php81
    - composer

static-code-analyzer: # Analyse static du code
  stage: code
  dependencies:
    - install
  script:
    - vendor/bin/phpstan analyse --level 3 src tests
  tags:
    - php81
    - composer

test:functional:
  stage: test
  dependencies:
    - install
  script:
    - composer test
  tags:
    - php81
    - composer
